kuttl: check cronjob nodeselectors, ignore pods created during init

diff --git a/tests/kuttl/tests/ctlplane-nodeselectors/02-assert-nodeselector.yaml b/tests/kuttl/tests/ctlplane-nodeselectors/02-assert-nodeselector.yaml
--- a/tests/kuttl/tests/ctlplane-nodeselectors/02-assert-nodeselector.yaml
+++ b/tests/kuttl/tests/ctlplane-nodeselectors/02-assert-nodeselector.yaml
@@ -5,10 +5,20 @@ commands:
   - script: |
       echo "Checking all pods have expected nodeselector"
       EXPECTED_NODE_SELECTOR="node-role.kubernetes.io/worker:"
-      BAD_OR_MISSING_NODE_SELECTOR=$(oc get pods -n $NAMESPACE -o=go-template --template='{{ range .items }}{{ .metadata.name}}: {{ .spec.nodeSelector }}{{"\n"}}{{ end }}' | sed -e '\!map\['"$EXPECTED_NODE_SELECTOR"'\]$!d')
+      BAD_OR_MISSING_NODE_SELECTOR=$(oc get pods -n $NAMESPACE -l skip_nodeselector_test!=true -o=go-template --template='{{ range .items }}{{ .metadata.name}}: {{ .spec.nodeSelector }}{{"\n"}}{{ end }}' | sed -e '\!map\['"$EXPECTED_NODE_SELECTOR"'\]$!d')
       BAD_OR_MISSING_NODE_SELECTOR_COUNT=$(echo "$BAD_OR_MISSING_NODE_SELECTOR" | wc -l)
       if [ $BAD_OR_MISSING_NODE_SELECTOR_COUNT -ne 0 ]; then
         echo "Found $BAD_OR_MISSING_NODE_SELECTOR_COUNT pods with bad or missing nodeselector:"
+        echo "$BAD_OR_MISSING_NODE_SELECTOR"
+        exit 1
+      fi
+  - script: |
+      echo "Checking all cronjobs have expected nodeselector"
+      EXPECTED_NODE_SELECTOR="node-role.kubernetes.io/worker:"
+      BAD_OR_MISSING_NODE_SELECTOR=$(oc get cronjobs -n $NAMESPACE -l skip_nodeselector_test!=true -o=go-template --template='{{ range .items }}{{ .metadata.name}}: {{ .spec.jobTemplate.spec.template.nodeSelector }}{{"\n"}}{{ end }}' | sed -e '\!map\['"$EXPECTED_NODE_SELECTOR"'\]$!d')
+      BAD_OR_MISSING_NODE_SELECTOR_COUNT=$(echo "$BAD_OR_MISSING_NODE_SELECTOR" | wc -l)
+      if [ $BAD_OR_MISSING_NODE_SELECTOR_COUNT -ne 0 ]; then
+        echo "Found $BAD_OR_MISSING_NODE_SELECTOR_COUNT cronjobs with bad or missing nodeselector:"
         echo "$BAD_OR_MISSING_NODE_SELECTOR"
         exit 1
       fi
